linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - maligned
linters-settings:
  maligned:
      # print struct with more effective memory layout or not, false by default
      suggest-new: true